-- 시퀀스 생성 --
CREATE SEQUENCE SEQ_NO
START WITH 1
MAXVALUE 2000;

COMMIT;

-- 테이블 생성 --
CREATE TABLE MOVIE_MAIN 
(
    NO NUMBER DEFAULT SEQ_NO.NEXTVAL PRIMARY KEY
    ,TITLE VARCHAR2(20)
    ,YEAR NUMBER
    ,RATING NUMBER
    ,GENRE NUMBER
);

CREATE TABLE MOVIE_GENRE
(
GENRE_NO NUMBER PRIMARY KEY
,GENRE_NAME VARCHAR2(20)
);

-- 제약조건 수정 --
ALTER TABLE MOVIE_MAIN
    ADD CONSTRAINT UK_YEAR UNIQUE (YEAR)
    ADD CONSTRAINT FK_GENRE FOREIGN KEY (GENRE)REFERENCES MOVIE_GENRE (GENRE_NO);

ALTER TABLE MOVIE_MAIN
    DROP CONSTRAINT UK_YEAR;
    
ALTER TABLE MOVIE_MAIN
    ADD CONSTRAINT UK_TITLE UNIQUE (TITLE);
    
-- MOVIE_GENRE 테이블 데이터 삽입 --
INSERT INTO MOVIE_GENRE
(
    GENRE_NO
    ,GENRE_NAME
)
VALUES
(
    400
    ,'드라마'
);
    
COMMIT;

-- MOVIE_MAIN 테이블 데이터 삽입 --
INSERT INTO MOVIE_MAIN
(
    TITLE
    ,YEAR
    ,RATING
    ,GENRE
)
VALUES
(
    '오펜하이머'
    ,2023
    ,5
    ,400
);

-- 제약조건, 데이터 수정 --
ALTER TABLE MOVIE_MAIN
    MODIFY TITLE VARCHAR2(40);
    
UPDATE MOVIE_MAIN
    SET RATING = 3
    WHERE TITLE = '동주';
    
DELETE MOVIE_MAIN
    WHERE TITLE = '탑건';
    -- 아래는 점검용 --
SELECT
        NO
        ,TITLE
        ,YEAR
        ,RATING
        ,GENRE
    FROM MOVIE_MAIN    ;
    
commit;

SELECT
        NO
        , TITLE
        , YEAR
        , RATING
        , GENRE
        FROM MOVIE_MAIN
        WHERE RATING BETWEEN 3 AND 4